DELIMITER //
CREATE TRIGGER ADICIONAR_VALOR
AFTER INSERT ON RECEITA
FOR EACH ROW
BEGIN
	
	UPDATE CARTEIRA SET CARTEIRA.SALDO = CARTEIRA.SALDO + NEW.VALOR where CARTEIRA.IDCARTEIRA = NEW.IDCARTEIRA;
end//
DELIMITER //


DELIMITER //
CREATE TRIGGER SUBTRAIR_VALOR
AFTER INSERT ON DESPESA
FOR EACH ROW
BEGIN
	
	UPDATE CARTEIRA SET CARTEIRA.SALDO = CARTEIRA.SALDO - NEW.VALOR where CARTEIRA.IDCARTEIRA = NEW.IDCARTEIRA;
    UPDATE META SET META.valor_comprido  = META.valor_comprido  + NEW.VALOR where META.IDCARTEIRA = NEW.IDCARTEIRA AND new.DATA LIKE concat(meta.DATA,'%');
end//
DELIMITER //

DELIMITER //
CREATE TRIGGER INSERIR_CARTEIRA
AFTER INSERT ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO CARTEIRA VALUES(default,0,NEW.IDUSUARIO);
end//
DELIMITER //
